### ISSUE TITLE
Consider enabling https for docs.gl?

### ISSUE THREAD

**Issue by nicolayr** [BSVino/docs.gl#81]
With SSL/TLS certificates being available [for free](https://letsencrypt.org/) and minimal impact with regard to performance (if any), it would be nice if docs.gl was hosted over https instead of http.

**Comment by BSVino** [comment]
That’s extra work and I’m crazy busy right now. What would users of the site gain from this?

**Comment by nicolayr** [comment]
Totally understandable. However SSL comes with many advantages and - once it's set up - no disadvantages compared to unencrypted web services. These days it should be considered the default for any public website.

If you share some info about the hosting setup you're using for docs.gl I would be happy to help you figure out what exactly needs to be done to enable SSL.

**Comment by BSVino** [comment]
Thank you. I know what has to be done as I’ve done it for other sites I host. I’m looking for specific advantages to the user of the site to justify it being worth my time right now. Docs.gl does no server side processing, stores no user information, no cookies, accepts no transactions or account info. Why is security necessary?

**Comment by nicolayr** [comment]
You can easily find articles and documentation about the advantages of SSL around the web, [this seems like a good summary](https://snyk.io/blog/10-reasons-to-use-https/) for instance.

To be clear it's not just for security. But saying that security isn't an issue for this site is a bit like saying you don't need seatbelts in a car that you'll only drive slowly. You're probably right that it's not a huge issue for this site, but in my opinion security should be the default, not something to hold off on until you start accepting credit card payments. Personally I prefer to stear away from sites that don't use SSL, so I made this suggestion because I really like docs.gl. But in any case it was just a suggestion and you are of course free to do as you see fit.

**Comment by BSVino** [comment]
Thanks for the suggestion. I appreciate that you care enough about docs.gl to make it. :)

I feel that right now none of these features are enough concretely better for the users of this particular website to justify the additional work. If I have to do any work in the future on the hosting of docs.gl then I'll look into grouping moving to https as a part of that work.

**Comment by editicalu** [comment]
I've hosted my own version on https://docs-gl.wardsegers.be. It supports HTTPS and IPv6.

If you need help with the transition to HTTPS, I'd be happy to help or host an HTTPS version.

**Comment by 1ace** [comment]
Came here to suggest enabling https://docs.gl, but I saw this discussion was already started so consider this my +1 :+1:

One thing that I often see missed from articles like the one @nicolayr mentioned is that SSL/TLS also protects users from injection, which has become a big use over the last few years with people injecting bitcoin miners (if you're lucky) into every http:// webpage opened by everyone on the same open wifi as them, like the ones in starbucks and such.

Serving your website on insecured HTTP doesn't just expose your server (which you might not care about since there's nothing on there), it also exposes all you visitors to these kinds of attacks :cry:

Please take 1-2 minutes to just have a look at the instructions on the website of the official client, certbot: https://certbot.eff.org/instructions  
Chances are your server setup supports the automation and you'll only need to run a single command to set up HTTPS, and add a second command to your crontab so that you never have to worry about it again.

Can I suggest you re-open this issue and leave it like that as a reminder that this is something that needs to be done at some point in the future, even if you don't have time to do it now?

**Comment by BSVino** [comment]
OK, you've convinced me. Now to just find the time...

**Comment by vktec** [comment]
Bump. Just discovered docs.gl and it looks awesome, but lack of HTTPS is dissuading me from using it.
If you need any additional convincing, it's worth noting that all recent browsers will display an "insecure" icon on unencrypted sites, which may deter visitors (myself included).

**Comment by BSVino** [comment]
I hear you. I'll try to set some time aside for it this weekend.

**Comment by BSVino** [comment]
I did it.

**Comment by nicolayr** [comment]
Awesome! 🥳 

You might also consider adding setting up [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security), although that's just icing on the cake ;)

**Comment by 1ace** [comment]
Ah, I came here to mention that the external scripts are currently broken and that I fixed it in #88 (as well as 1500 other fixes), but I see @nicolayr sent a fix for the 4 scripts urls in #87 a few minutes before me :sweat_smile:

@BSVino if you want to merge #87 first, I'll rebase #88 so you can merge it as well :+1:
(otherwise, you can also just merge #88 since it contains everything #87 does)

**Comment by nicolayr** [comment]
My PR was quick and dirty so sounds like #88 is a better bet 😉

**Comment by BSVino** [comment]
What a silly oversight. Thanks to both of you, I'm incredibly grateful. It looks like @nicolayr's changes are included in @1ace's patch so I'm merging the latter and closing the former. When it's done I'll do another check to make sure everything is working OK. I don't have much experience as a website administrator so this is all very useful and much appreciated.

**Comment by BSVino** [comment]
The upload is complete but there's a 24 hour cache. I'll check again tomorrow.
